changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking change
    - title: Bug Fixes
      labels:
        - bug
    - title: All Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
