name: Manually Create Release

on:
  workflow_dispatch:
    inputs:
      release_name: 
        description: Release name to create
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          tag: ${{ inputs.release_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="v${tag#v}" \
              --generate-notes